### ISSUE TITLE
missing link, home page

### ISSUE THREAD

**Issue by AnnaWilliford** [datacarpentry/R-genomics#48]
'Data Carpentry: R for Genomics' home page, under Data:
"Data files for the lesson are available and can be downloaded manually here:"  No link

**Comment by JasonJWilliamsNY** [comment]
I think this needs to be removed. I am assuming that we are only supporting cloud at this time although this may change.

**Comment by naupaka** [comment]
I added a link to the csv in https://github.com/naupaka/R-genomics/commit/8506d5ede3857005bef49535b268d5ab03562b04, but I agree we will need to revisit this when we decide if this is going to be a local or a cloud-based lesson. Currently, the rest of the setup is local, so it makes sense to have this link in there.

**Comment by ErinBecker** [comment]
Closed with https://github.com/datacarpentry/R-genomics/pull/77
