### ISSUE TITLE
Intro to R; typo + give examples

### ISSUE THREAD

**Issue by AnnaWilliford** [datacarpentry/R-genomics#71]
Under "Notes on objects":
"In doubt check the help to see if the name is already in use. "
"If in doubt..." 
And how to do that? give example

"When assigning a value to an object, R does not print anything. You can force to print the value by using parentheses or by typing the name:"  Looks like the examples should follow...

**Comment by ErinBecker** [comment]
Closed with https://github.com/datacarpentry/R-genomics/pull/77
