### ISSUE TITLE
Episode Starting with data; no need to create an additional data directory

### ISSUE THREAD

**Issue by AnnaWilliford** [datacarpentry/R-genomics#75]
In "Before we start" episode, we created the directory structure that includes data directory.
In "Starting with data", download.file() puts Ecoli_metadata.csv into directly data directory. 

The following steps should be removed:
"First, make sure you are in the correct working directory by typing getwd()
Second, create a new subdirectory within this working directory called data
Third, move the just-downloaded Ecoli_metadata.csv file into this data directory"

It is better to check if you are in the right directory before running download.file()

And what is this about? (just before the download.file() command? Confused.
"
If you see and error in response to download.file(), you may need to change the directory "~/Downloads/portal_data_joined.csv"  "

**Comment by JasonJWilliamsNY** [comment]
Agreed. In http://www.datacarpentry.org/R-genomics/02-starting-with-data.html "Starting with Data" we should remove the download.file() as the data will already be there. 

Alternative this whole section

>OR
    Use R to download the file by giving the download.file() function the link address for the file, and        
    where you want to put this file. If you see and error in response to download.file(), you may need 
    to change the directory "~/Downloads/portal_data_joined.csv"

    download.file("https://raw.githubusercontent.com/datacarpentry/R-genomics/gh-pages/data  
    /Ecoli_metadata.csv",
                  "data/Ecoli_metadata.csv")
        First, make sure you are in the correct working directory by typing getwd()
        Second, create a new subdirectory within this working directory called data
        Third, move the just-downloaded Ecoli_metadata.csv file into this data directory

Could be formatted so that it is clear this is an alternative (presuming that someone does not have cloud access?

**Comment by ErinBecker** [comment]
Closed with https://github.com/datacarpentry/R-genomics/pull/78
